## Server settings
#server.port=8080
#spring.application.name=smart-bank-system

# --- DISABLED H2 DATABASE CONFIGURATION ---
# spring.datasource.url=jdbc:h2:mem:bankdb
# spring.datasource.driverClassName=org.h2.Driver
# spring.datasource.username=sa
# spring.datasource.password=
# spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# spring.h2.console.enabled=true
# spring.h2.console.path=/h2-console

# --- ACTIVE TiDB CLOUD CONFIGURATION ---
spring.datasource.url=jdbc:mysql://gateway01.us-east-1.prod.aws.tidbcloud.com:4000/smartbank?useSSL=true&enabledTLSProtocols=TLSv1.2,TLSv1.3
spring.datasource.username=4D1CDNnkJgm4Ajm.root
spring.datasource.password=T19eTvlfQGFrZU9F
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate Persistent Lifecycle Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Fix Spring Security credentials so they never change on restart
spring.security.user.name=${SECURITY_USER}
spring.security.user.password=${SECURITY_PASSWORD}